export enum CredentialStatus {
  PENDING = "PENDING",
  ACTIVATED = "ACTIVATED",
  LOCKED = "LOCKED",
  BLOCKED = "BLOCKED",
  COMPROMISED = "COMPROMISED",
  REACTIVATING = "REACTIVATING",
  DISABLED = "DISABLED",
}
