enum CredentialStatus {
  PENDING = "PENDING",
  ACTIVATED = "ACTIVATED",
  LOCKED = "LOCKED",
  BLOCKED = "BLOCKED",
  COMPROMISED = "COMPROMISED",
  REACTIVATING = "REACTIVATING",
  DISABLED = "DISABLED",
}

enum SentinelStatus {
  INCONSISTENT_REGISTRATION = "S01IR",
  CREDENTIALS_DEFINITION_REQUIRED = "S02CDR",
  MFA_DATA_GENERATED = "SC03DG",
  MFA_ENROLLMENT_CONFIRMATION_REQUIRED = "S04ECR"
}

export {
  CredentialStatus,
  SentinelStatus
}
